Repository GitLabPHP/Client, pull requests merged in 2021-12, with the labels that each got.

#680 [11.5] Add `deleteProtectedBranch` method to projects api
  src/Api/Projects.php
  tests/Api/ProjectsTest.php
Labels: enhancement

#682 [11.4] Fix double encoding of query parameters in `Repositories::compare`
  src/Api/Repositories.php
  tests/Api/RepositoriesTest.php
Labels: bug

#654 [11.5] Fix release creation/update API paths
  src/Api/Repositories.php
  tests/Api/RepositoriesTest.php
Labels: bug, broken-tests, changes-required
